export type MasterCardKind = 'Tamer' | 'Hoodmon' | 'Magic' | 'Trap' | 'Field' | 'Task'

export interface MasterCardMetadata {
  id: string
  name: string
  kind: MasterCardKind
  rarity: string
  alignment: string[]
  traits: string[]
  cost?: number
  bondCost?: number
  atk?: number
  hp?: number
  taskRating?: number
  stageLevel?: 1 | 2 | 3 | 4
  taskDifficulty?: number
  magicSubtype?: 'Standard' | 'Quick' | 'Continuous' | 'Equipment'
}

export const masterCardMetadata: MasterCardMetadata[] = [
  { id: "HDM-001", name: "O.D.D. Paul", kind: "Tamer" as MasterCardKind, rarity: "SR", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], cost: 3 },
  { id: "HDM-002", name: "Alley Pup", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], bondCost: 1, atk: 400, hp: 700, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-003", name: "Bluefang Hound", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], bondCost: 3, atk: 900, hp: 1600, taskRating: 400, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-004", name: "Drunk Fist Wulf", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], bondCost: 5, atk: 1600, hp: 2800, taskRating: 700, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-005", name: "Loyal Packmate", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], bondCost: 1, atk: 300, hp: 600, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-006", name: "Back Alley Guardian", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], bondCost: 3, atk: 800, hp: 1500, taskRating: 300, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-007", name: "Concrete Warden", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Neighborhood Loyalty", "Beast"], bondCost: 5, atk: 1600, hp: 2600, taskRating: 600, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-008", name: "Corner Store Den", kind: "Field" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Neighborhood Loyalty"], cost: 2 },
  { id: "HDM-009", name: "Good Dogs Great People", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: [], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-010", name: "Puppy Chow Promise", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Beast"], traits: [], taskDifficulty: 100 },
  { id: "HDM-011", name: "Corner Bowl Offering", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Beast"], traits: [], taskDifficulty: 100 },
  { id: "HDM-012", name: "Drunken Fist Lesson", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Neighborhood Loyalty"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-013", name: "Pack Howl Rally", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: [], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-014", name: "Neighborhood Watch", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: [], cost: 2 },
  { id: "HDM-015", name: "Street Guardian Oath", kind: "Trap" as MasterCardKind, rarity: "SR", alignment: ["Beast"], traits: [], cost: 3 },
  { id: "HDM-016", name: "Cinnamon", kind: "Tamer" as MasterCardKind, rarity: "SR", alignment: ["Wind", "Psychic"], traits: ["Bird-Tech Block", "Bird", "Tech"], cost: 2 },
  { id: "HDM-017", name: "Squab", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Wind"], traits: ["Bird-Tech Block", "Bird", "Tech"], bondCost: 1, atk: 250, hp: 700, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-018", name: "Sky Rat", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Wind", "Psychic"], traits: ["Bird-Tech Block", "Bird", "Tech"], bondCost: 3, atk: 800, hp: 1400, taskRating: 300, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-019", name: "Bird Brain", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Wind", "Psychic"], traits: ["Bird-Tech Block", "Bird", "Tech"], bondCost: 5, atk: 1500, hp: 2400, taskRating: 600, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-020", name: "Block Pigeon", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Wind"], traits: ["Bird-Tech Block", "Bird", "Tech"], bondCost: 1, atk: 300, hp: 600, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-021", name: "Rooftop Bully", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Wind", "Beast"], traits: ["Bird-Tech Block", "Bird"], bondCost: 2, atk: 850, hp: 1500, taskRating: 300, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-022", name: "Same Block, Different Generation", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Wind"], traits: ["Bird-Tech Block", "Bird", "Tech"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-023", name: "Neighborhood Wi-Fi", kind: "Field" as MasterCardKind, rarity: "R", alignment: ["Wind"], traits: ["Bird-Tech Block", "Tech"], cost: 2 },
  { id: "HDM-024", name: "Bird's-Eye Backdoor", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Psychic"], traits: ["Bird-Tech Block", "Tech"], cost: 1, magicSubtype: "Quick" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-025", name: "Good Neighbors Share Passwords", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Wind"], traits: ["Bird-Tech Block", "Tech"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-026", name: "Don't Touch That Camera", kind: "Trap" as MasterCardKind, rarity: "U", alignment: ["Wind"], traits: ["Bird-Tech Block", "Tech"], cost: 0 },
  { id: "HDM-027", name: "Pigeon-Grade Cybersecurity", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Psychic"], traits: ["Bird-Tech Block", "Tech"], cost: 0 },
  { id: "HDM-028", name: "Check on the Block", kind: "Task" as MasterCardKind, rarity: "C", alignment: [], traits: [], taskDifficulty: 100 },
  { id: "HDM-029", name: "Everybody Eats", kind: "Task" as MasterCardKind, rarity: "U", alignment: [], traits: [], taskDifficulty: 100 },
  { id: "HDM-030", name: "Peaches", kind: "Tamer" as MasterCardKind, rarity: "U", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm", "Pit Bull"], cost: 3 },
  { id: "HDM-031", name: "Puppy", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: ["Pack Pressure", "Pit Bull"], bondCost: 1, atk: 300, hp: 700, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-032", name: "Brawler", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: ["Pack Pressure", "Pit Bull"], bondCost: 3, atk: 900, hp: 1800, taskRating: 400, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-033", name: "Redline", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: ["Pack Pressure", "Pit Bull"], bondCost: 5, atk: 1600, hp: 2800, taskRating: 700, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-034", name: "Chainjaw Pup", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Pit Bull"], bondCost: 1, atk: 400, hp: 900, taskRating: 200, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-035", name: "Velvet Mauler", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Pit Bull"], bondCost: 3, atk: 1000, hp: 2000, taskRating: 400, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-036", name: "I Know My Worth", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-037", name: "Iron Jaw Lock", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Pack Pressure", "Charm"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-038", name: "Pretty Girls Raise Monsters", kind: "Magic" as MasterCardKind, rarity: "SR", alignment: ["Beast"], traits: ["Pack Pressure", "Charm"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-039", name: "Off the Leash", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Beast"], traits: ["Pack Pressure", "Charm"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-040", name: "Bad Idea, Babe", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm"], cost: 2 },
  { id: "HDM-041", name: "Chain Break Counter", kind: "Trap" as MasterCardKind, rarity: "SR", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm"], cost: 2 },
  { id: "HDM-042", name: "Velvet Block Kennel", kind: "Field" as MasterCardKind, rarity: "R", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm"], cost: 2 },
  { id: "HDM-043", name: "Cash In When It Counts", kind: "Task" as MasterCardKind, rarity: "U", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm"], taskDifficulty: 100 },
  { id: "HDM-044", name: "Walk Him Down", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Beast", "Dark"], traits: ["Pack Pressure", "Charm"], taskDifficulty: 100 },
  { id: "HDM-045", name: "Street Contract", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Beast"], traits: ["Pack Pressure", "Street Magic"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-046", name: "Cherry Banks", kind: "Tamer" as MasterCardKind, rarity: "SR", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm", "Feline", "Shadow"], cost: 3 },
  { id: "HDM-047", name: "Kitten", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm", "Feline", "Shadow"], bondCost: 1, atk: 300, hp: 700, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-048", name: "Shadowcat", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm", "Feline", "Shadow"], bondCost: 3, atk: 800, hp: 1500, taskRating: 300, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-049", name: "Miso", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm", "Feline", "Shadow"], bondCost: 5, atk: 1500, hp: 2600, taskRating: 600, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-050", name: "Velvet Paw Scout", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm", "Feline", "Shadow"], bondCost: 1, atk: 300, hp: 500, taskRating: 200, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-051", name: "Moonlit Hideout", kind: "Field" as MasterCardKind, rarity: "R", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 2 },
  { id: "HDM-052", name: "Silent Claws", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-053", name: "Shadow Step", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-054", name: "Rooftop Informant", kind: "Hoodmon" as MasterCardKind, rarity: "U", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm", "Feline", "Intel"], bondCost: 2, atk: 500, hp: 800, taskRating: 200, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-055", name: "Marked for Midnight", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], taskDifficulty: 100 },
  { id: "HDM-056", name: "Smoke Screen Alibi", kind: "Trap" as MasterCardKind, rarity: "U", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 2 },
  { id: "HDM-057", name: "Nine Lives Escape", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 2 },
  { id: "HDM-058", name: "Dead Drop Message", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], taskDifficulty: 100 },
  { id: "HDM-059", name: "Blackmail File", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-060", name: "Perfect Getaway", kind: "Trap" as MasterCardKind, rarity: "SR", alignment: ["Dark", "Fairy"], traits: ["High-Class Charm"], cost: 3 },
  { id: "HDM-061", name: "Leaked Evidence", kind: "Magic" as MasterCardKind, rarity: "SP", alignment: ["Dark"], traits: ["High-Class Charm", "Tech"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-062", name: "Data Snatch", kind: "Task" as MasterCardKind, rarity: "R", alignment: ["Dark"], traits: ["High-Class Charm", "Tech"], taskDifficulty: 100 },
  { id: "HDM-063", name: "Tax Rell", kind: "Tamer" as MasterCardKind, rarity: "U", alignment: ["Water", "Smoke"], traits: ["Mist Network"], cost: 3 },
  { id: "HDM-064", name: "Mistling", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Water"], traits: ["Mist Network", "Reptile"], bondCost: 1, atk: 400, hp: 800, taskRating: 200, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-065", name: "Vaporgeck", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Water", "Nature"], traits: ["Mist Network", "Reptile"], bondCost: 3, atk: 900, hp: 1600, taskRating: 400, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-066", name: "Nebulizard", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Water", "Smoke"], traits: ["Mist Network", "Reptile", "Ninja"], bondCost: 5, atk: 1600, hp: 2800, taskRating: 700, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-067", name: "Rooftop Condensation", kind: "Field" as MasterCardKind, rarity: "U", alignment: ["Water"], traits: ["Mist Network"], cost: 2 },
  { id: "HDM-068", name: "Dewdrop Cache", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Water"], traits: ["Mist Network"], taskDifficulty: 200 },
  { id: "HDM-069", name: "Spotlet", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Smoke"], traits: ["Mist Network", "Reptile", "Smoke", "Ninja"], bondCost: 1, atk: 300, hp: 700, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-070", name: "Vapor Cache", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Water", "Nature"], traits: ["Mist Network"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-071", name: "Gecko Ambush", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Water", "Nature"], traits: ["Mist Network"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-072", name: "Mist Network", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Water", "Smoke"], traits: ["Mist Network"], cost: 2 },
  { id: "HDM-073", name: "Smokescreen Slip", kind: "Trap" as MasterCardKind, rarity: "U", alignment: ["Smoke"], traits: ["Mist Network"], cost: 1 },
  { id: "HDM-074", name: "Urban Mist Network", kind: "Field" as MasterCardKind, rarity: "R", alignment: ["Water", "Smoke"], traits: ["Mist Network"], cost: 2 },
  { id: "HDM-075", name: "Mist Map", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Water"], traits: ["Mist Network"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-076", name: "Tiny Creatures, Bigger Moves", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Water"], traits: ["Mist Network"], taskDifficulty: 700 },
  { id: "HDM-077", name: "What You Don't See... Obeys", kind: "Trap" as MasterCardKind, rarity: "SR", alignment: ["Water", "Smoke"], traits: ["Mist Network"], cost: 3 },
  { id: "HDM-078", name: "Capin MDH", kind: "Tamer" as MasterCardKind, rarity: "SR", alignment: ["Psychic"], traits: ["Truth Network"], cost: 3 },
  { id: "HDM-079", name: "Kitklaws", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Psychic", "Dark"], traits: ["Truth Network"], bondCost: 1, atk: 300, hp: 600, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-080", name: "Scratchwiser", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Dark", "Psychic"], traits: ["Truth Network"], bondCost: 3, atk: 800, hp: 1400, taskRating: 300, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-081", name: "Calicore", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Psychic", "Light"], traits: ["Truth Network"], bondCost: 5, atk: 1500, hp: 2500, taskRating: 600, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-082", name: "Monical", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Psychic", "Light"], traits: ["Truth Network"], bondCost: 7, atk: 2200, hp: 3400, taskRating: 900, stageLevel: 4 as 1 | 2 | 3 | 4 },
  { id: "HDM-083", name: "Hoodmon Truth Network", kind: "Field" as MasterCardKind, rarity: "R", alignment: ["Psychic"], traits: ["Truth Network"], cost: 2 },
  { id: "HDM-084", name: "Data Over Fear", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Psychic"], traits: ["Truth Network"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-085", name: "Research, Record, Reveal!", kind: "Task" as MasterCardKind, rarity: "C", alignment: ["Psychic"], traits: [], taskDifficulty: 100 },
  { id: "HDM-086", name: "Signal Intercept", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Psychic"], traits: ["Truth Network", "Tech"], cost: 2 },
  { id: "HDM-087", name: "Field Notes Archive", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-088", name: "Eyewitness Report", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-089", name: "Hidden Pattern Decode", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-090", name: "On Air Tonight", kind: "Field" as MasterCardKind, rarity: "C", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 1 },
  { id: "HDM-091", name: "Expose the Cover-Up", kind: "Trap" as MasterCardKind, rarity: "SR", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 3 },
  { id: "HDM-092", name: "Oracle's Data Stream", kind: "Magic" as MasterCardKind, rarity: "SR", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 3, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-093", name: "Status System Leak", kind: "Magic" as MasterCardKind, rarity: "SR", alignment: ["Psychic"], traits: ["Truth Network", "Research"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-094", name: "EB & Igniscale", kind: "Tamer" as MasterCardKind, rarity: "SR", alignment: ["Fire", "Dark"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Igniscale"], cost: 3 },
  { id: "HDM-095", name: "Ember Hatchling", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Fire"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Bright Flame"], bondCost: 1, atk: 300, hp: 600, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-096", name: "Smoldering Beard", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Fire"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Bright Flame"], bondCost: 3, atk: 900, hp: 1600, taskRating: 400, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-097", name: "Ashen Warden", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Fire"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Bright Flame"], bondCost: 5, atk: 1600, hp: 2800, taskRating: 700, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-098", name: "Shadow Hatchling", kind: "Hoodmon" as MasterCardKind, rarity: "C", alignment: ["Dark", "Fire"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Shadow Ember", "Igniscale"], bondCost: 1, atk: 300, hp: 600, taskRating: 100, stageLevel: 1 as 1 | 2 | 3 | 4 },
  { id: "HDM-099", name: "Duskwyrm", kind: "Hoodmon" as MasterCardKind, rarity: "R", alignment: ["Dark", "Fire"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Shadow Ember", "Igniscale"], bondCost: 3, atk: 850, hp: 1500, taskRating: 350, stageLevel: 2 as 1 | 2 | 3 | 4 },
  { id: "HDM-100", name: "Abyss Igniscale", kind: "Hoodmon" as MasterCardKind, rarity: "SR", alignment: ["Dark", "Fire"], traits: ["Dual Flame Bond", "Bearded Dragon", "Reptile", "Shadow Ember", "Igniscale"], bondCost: 5, atk: 1600, hp: 2700, taskRating: 700, stageLevel: 3 as 1 | 2 | 3 | 4 },
  { id: "HDM-101", name: "Different Blood, Same Loyalty", kind: "Magic" as MasterCardKind, rarity: "U", alignment: ["Fire", "Dark"], traits: ["Dual Flame Bond", "Bright Flame", "Shadow Ember", "Bearded Dragon"], cost: 1, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-102", name: "Street Sweetheart Pact", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Fire", "Beast"], traits: ["Dual Flame Bond", "Pack Pressure", "Bearded Dragon", "Pit Bull", "Peaches"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-103", name: "Reserve Roll Call", kind: "Task" as MasterCardKind, rarity: "C", alignment: [], traits: ["Dual Flame Bond", "Reserve", "Bearded Dragon"], cost: 1 },
  { id: "HDM-104", name: "Flame Tag-Out", kind: "Trap" as MasterCardKind, rarity: "R", alignment: ["Fire", "Dark"], traits: ["Dual Flame Bond", "Bearded Dragon", "Bright Flame", "Shadow Ember"], cost: 2 },
  { id: "HDM-105", name: "Split Flames, One Family", kind: "Field" as MasterCardKind, rarity: "U", alignment: ["Fire", "Dark"], traits: ["Dual Flame Bond", "Bearded Dragon", "Bright Flame", "Shadow Ember"], cost: 2 },
  { id: "HDM-106", name: "Shadowfire Exchange", kind: "Magic" as MasterCardKind, rarity: "R", alignment: ["Fire", "Dark"], traits: ["Dual Flame Bond", "Bearded Dragon", "Bright Flame", "Shadow Ember"], cost: 2, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-107", name: "Peaches' Backup Bite", kind: "Trap" as MasterCardKind, rarity: "SR", alignment: ["Fire", "Beast"], traits: ["Dual Flame Bond", "Pack Pressure", "Bearded Dragon", "Pit Bull", "Peaches"], cost: 3 },
  { id: "HDM-108", name: "Blockfire Kennel", kind: "Field" as MasterCardKind, rarity: "U", alignment: ["Fire", "Beast"], traits: ["Dual Flame Bond", "Pack Pressure", "Bearded Dragon", "Pit Bull"], cost: 2 },
  { id: "HDM-109", name: "Dual Line Awakening", kind: "Magic" as MasterCardKind, rarity: "SR", alignment: ["Fire", "Dark"], traits: ["Dual Flame Bond", "Bearded Dragon", "Bright Flame", "Shadow Ember"], cost: 3, magicSubtype: "Standard" as MasterCardMetadata['magicSubtype'] },
  { id: "HDM-110", name: "Crash Their Feed", kind: "Task" as MasterCardKind, rarity: "R", alignment: [], traits: ["Bird-Tech Block", "Tech"], cost: 1 },
]

export const masterMetadataById = Object.fromEntries(masterCardMetadata.map((card) => [card.id, card])) as Record<string, MasterCardMetadata>
